# Generated by Django 5.0.14 on 2026-08-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='allowed_role',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visibility',
        ),
    ]
