# Generated by Django 5.0.14 on 2026-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_allowed_role_remove_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption_mac_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='encrypted_thumbnail_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
