# Generated by Django 5.0.14 on 2026-08-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
