# Generated by Django 5.0.14 on 2026-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorsettings',
            name='answer_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='twofactorsettings',
            name='question',
            field=models.CharField(blank=True, choices=[('first_teacher', 'What was the name of your first teacher?'), ('first_pet', 'What was the name of your first pet?'), ('birth_city', 'In which city were you born?'), ('childhood_friend', 'What is the name of your childhood best friend?'), ('primary_school', 'What was the name of your primary school?'), ('favourite_dish', 'What is your favourite dish?'), ('mothers_maiden_name', "What is your mother's maiden name?")], max_length=32),
        ),
        migrations.AlterField(
            model_name='twofactorsettings',
            name='method',
            field=models.CharField(choices=[('security_question', 'Security Question')], default='security_question', max_length=32),
        ),
    ]
