# Generated by Django 5.0.14 on 2026-09-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_twofactorsettings_answer_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorsettings',
            name='answer_hash',
        ),
        migrations.RemoveField(
            model_name='twofactorsettings',
            name='question',
        ),
        migrations.AlterField(
            model_name='twofactorsettings',
            name='method',
            field=models.CharField(choices=[('totp', 'Authenticator App (TOTP)')], default='totp', max_length=32),
        ),
    ]
