# Generated by Django 5.0.14 on 2026-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_twofactorsettings_answer_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_mac_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='encrypted_avatar_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
