# Generated by Django 5.0.14 on 2026-09-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_image_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_mac_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
